export default function TermsPage() {
  return (
    <div className="prose prose-invert max-w-2xl text-sm" style={{ color: "var(--text-secondary)" }}>
      <h1 className="text-2xl font-semibold" style={{ color: "var(--text-primary)" }}>
        Terms &amp; Conditions
      </h1>
      <p className="mt-1 text-xs" style={{ color: "var(--text-tertiary)" }}>
        Last updated: draft — pending final legal sign-off.
      </p>

      <h2 className="mt-6 text-base font-semibold" style={{ color: "var(--text-primary)" }}>
        1. What AlphaTrade Signals is
      </h2>
      <p>
        AlphaTrade Signals publishes trading signals and performance
        statistics for cryptocurrency and forex instruments, generated by
        automated strategies, third-party providers, and human analysts.
        Signals are published for informational and educational purposes
        only.
      </p>

      <h2 className="mt-6 text-base font-semibold" style={{ color: "var(--text-primary)" }}>
        2. Not investment advice
      </h2>
      <p>
        Nothing on this platform constitutes investment, financial, legal,
        or tax advice, and no signal, score, or statistic is a
        recommendation to buy or sell any instrument. You are solely
        responsible for your own trading decisions. AlphaTrade Signals is
        not a registered investment adviser or broker-dealer.
      </p>

      <h2 className="mt-6 text-base font-semibold" style={{ color: "var(--text-primary)" }}>
        3. Risk disclosure
      </h2>
      <p>
        Trading cryptocurrencies and forex carries substantial risk of
        loss, including the potential loss of your entire investment. Past
        performance of any signal, strategy, or analyst — including
        AlphaScore, win rate, or any other statistic shown on this
        platform — does not guarantee or predict future results. No profit
        is promised or implied.
      </p>

      <h2 className="mt-6 text-base font-semibold" style={{ color: "var(--text-primary)" }}>
        4. Accounts and subscriptions
      </h2>
      <p>
        Some signals and features are restricted to paid Premium
        subscribers. Subscriptions are billed on a recurring basis through
        our payment processor (Paystack) until cancelled. Fees are
        non-refundable except where required by law.
      </p>

      <h2 className="mt-6 text-base font-semibold" style={{ color: "var(--text-primary)" }}>
        5. No liability for trading losses
      </h2>
      <p>
        To the fullest extent permitted by law, AlphaTrade Signals and its
        operators are not liable for any trading losses, missed gains, or
        other damages arising from your use of, or reliance on, any
        content published on this platform.
      </p>

      <h2 className="mt-6 text-base font-semibold" style={{ color: "var(--text-primary)" }}>
        6. Changes
      </h2>
      <p>
        These terms may be updated from time to time. Continued use of the
        platform after a change constitutes acceptance of the revised
        terms.
      </p>

      <p className="mt-8 text-xs" style={{ color: "var(--text-tertiary)" }}>
        This draft covers the core disclaimers a signals platform typically
        needs, but jurisdiction-specific clauses (governing law, dispute
        resolution, data protection under NDPR, consumer protection) should
        still be finalized with your lawyer before this is treated as final.
      </p>
    </div>
  );
}
